Habit details
NoJonesAcademy/NoJones pull request #11
Opened 2020-05-04 21:30 UTC by viniciusmesquitac

2020-05-04 23:56 UTC, ViniciusDeep requested changes

2020-05-04 23:56 UTC, ViniciusDeep commented on NoJones/Controller/DashboardViewController.swift
> -        //        if let userName = UserDefaultsManager.fetchString(withUserDefaultKey: .userName) {
Apagar esses comentários

2020-05-04 23:56 UTC, ViniciusDeep commented on NoJones/Controller/DashboardViewController.swift
>          noAddictionMessage.frame.size.height = self.addictions.isEmpty ? 220 : 0
Quanto for usar magic number como nesses casos: ``` 220 ``` é bom tu explicar isso em um Enum da vida, ou uma struct,  exemplo

```
enum Constants: CGFloat {
    case dashBoardTableViewHeaderHeight = 2200
}
```

caso de uso: ```  tableView.heightForHeader = Constants.dashBoardTableViewHeaderHeight.rawValue ```

Vantagem: Tu não cria code smell de magic number no teu código, que depois vai dar muito trabalho de manter

2020-05-04 23:56 UTC, ViniciusDeep commented on NoJones/Controller/DashboardViewController.swift
> +        performSegue(withIdentifier: SegueDestination.HabitDetails.rawValue, sender: self)
Boa

2020-05-04 23:56 UTC, ViniciusDeep commented on NoJones/Controller/DashboardViewController.swift
> +
Remover espaços desnecessários

2020-05-04 23:56 UTC, ViniciusDeep commented on NoJones/Controller/HabitDetailsViewController.swift
> +    var habits: [Addiction]?
Porque ```habits``` não é um array de habit?

2020-05-04 23:56 UTC, ViniciusDeep commented on NoJones/Controller/HabitDetailsViewController.swift
> +           print(habits)
Remover esse print, e o IF let

2020-05-04 23:56 UTC, ViniciusDeep commented on NoJones/Controller/HabitDetailsViewController.swift
> +
Espaços desnecessários.

2020-05-04 23:56 UTC, ViniciusDeep commented on NoJones/CustomView/DayWeekCustomView.swift
> +//        self.imageMark.backgroundColor = UIColor(named: "buttonColor")
Remover comentário

2020-05-04 23:56 UTC, ViniciusDeep commented on NoJones/Protocols/DashboardDelegate.swift
> +    func sendHabitDetails(habits: [Addiction])
Normalmente em ```delegates``` usamos did nos métodos, pois normalmente você está passando algo

2020-05-04 23:56 UTC, ViniciusDeep commented on NoJones/Router/SegueRoute.swift
> +    case HabitDetails = "detailSegue"
Massa, isso evita code smell em controller

2020-05-04 23:59 UTC, viniciusmesquitac commented on NoJones/Controller/HabitDetailsViewController.swift
> +    var habits: [Addiction]?
addicion vai virar habits em um futuro proximo ahuahua

2020-05-05 00:13 UTC, viniciusmesquitac commented on NoJones/Controller/DashboardViewController.swift
> +
Done

2020-05-05 00:13 UTC, viniciusmesquitac commented on NoJones/Controller/HabitDetailsViewController.swift
> +           print(habits)
Done

2020-05-05 00:18 UTC, viniciusmesquitac commented on NoJones/Controller/DashboardViewController.swift
> -        //        if let userName = UserDefaultsManager.fetchString(withUserDefaultKey: .userName) {
Done

2020-05-05 12:02 UTC, NobreMateus commented
ok

2020-05-05 12:04 UTC, NobreMateus approved these changes
Muito Bom

2020-05-05 12:04 UTC, AlbertQueiroz approved these changes
Ok

2020-05-05 12:05 UTC, merged